#include "tahini_client.h"

#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <unistd.h>

#define TAHINI_MAX_DOCUMENT (256 * 1024)
#define TAHINI_DEFAULT_TIMEOUT_MS 5000

static char g_error[256] = "no error";

static int fail(int code, const char* fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(g_error, sizeof(g_error), fmt, ap);
    va_end(ap);
    return code;
}

const char* tahini_last_error(void) { return g_error; }

void tahini_attestation_free(tahini_attestation* out) {
    if (!out) return;
    free(out->binary_hash);
    free(out->quote);
    free(out->verification_info);
    memset(out, 0, sizeof(*out));
}

// The document is generated by u_attest.c and its shape is fixed, so these
// extractors target that shape rather than parsing JSON in general. They are
// strict about what they accept: a field that is missing or not the expected kind
// is a protocol error, not a NULL that flows onward as if it were data.
static char* extract_string(const char* doc, const char* key) {
    char pattern[64];
    snprintf(pattern, sizeof(pattern), "\"%s\"", key);
    const char* p = strstr(doc, pattern);
    if (!p) return NULL;
    p = strchr(p + strlen(pattern), ':');
    if (!p) return NULL;
    p++;
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    if (*p != '"') return NULL;
    p++;
    const char* end = strchr(p, '"');
    if (!end) return NULL;
    size_t n = (size_t)(end - p);
    char* v = malloc(n + 1);
    if (!v) return NULL;
    memcpy(v, p, n);
    v[n] = '\0';
    return v;
}

// Returns the balanced {...} value for `key`, so the caller receives the nested
// object verbatim and can hand it to a real JSON parser.
static char* extract_object(const char* doc, const char* key) {
    char pattern[64];
    snprintf(pattern, sizeof(pattern), "\"%s\"", key);
    const char* p = strstr(doc, pattern);
    if (!p) return NULL;
    p = strchr(p + strlen(pattern), ':');
    if (!p) return NULL;
    p++;
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    if (*p != '{') return NULL;

    // Depth counting, with string awareness so a brace inside a value does not
    // end the object early.
    int depth = 0;
    int in_string = 0;
    const char* start = p;
    for (; *p; p++) {
        if (in_string) {
            if (*p == '\\' && p[1]) { p++; continue; }
            if (*p == '"') in_string = 0;
            continue;
        }
        if (*p == '"') { in_string = 1; continue; }
        if (*p == '{') depth++;
        else if (*p == '}') {
            depth--;
            if (depth == 0) {
                size_t n = (size_t)(p - start) + 1;
                char* v = malloc(n + 1);
                if (!v) return NULL;
                memcpy(v, start, n);
                v[n] = '\0';
                return v;
            }
        }
    }
    return NULL;
}

static int extract_int(const char* doc, const char* key, int* out) {
    char pattern[64];
    snprintf(pattern, sizeof(pattern), "\"%s\"", key);
    const char* p = strstr(doc, pattern);
    if (!p) return -1;
    p = strchr(p + strlen(pattern), ':');
    if (!p) return -1;
    char* end = NULL;
    long v = strtol(p + 1, &end, 10);
    if (end == p + 1) return -1;
    *out = (int)v;
    return 0;
}

int tahini_fetch_attestation(const char* ip, uint16_t port, uint32_t timeout_ms,
                             tahini_attestation* out) {
    if (!ip || !out || port == 0) return fail(TAHINI_ERR_ARGS, "bad arguments");
    memset(out, 0, sizeof(*out));
    if (timeout_ms == 0) timeout_ms = TAHINI_DEFAULT_TIMEOUT_MS;

    struct sockaddr_in sa;
    memset(&sa, 0, sizeof(sa));
    sa.sin_family = AF_INET;
    sa.sin_port = htons(port);
    if (inet_pton(AF_INET, ip, &sa.sin_addr) != 1)
        return fail(TAHINI_ERR_ARGS, "'%s' is not an IPv4 address", ip);

    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) return fail(TAHINI_ERR_CONNECT, "socket: %s", strerror(errno));

    struct timeval tv;
    tv.tv_sec = (time_t)(timeout_ms / 1000);
    tv.tv_usec = (suseconds_t)((timeout_ms % 1000) * 1000);
    setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));

    if (connect(fd, (struct sockaddr*)&sa, sizeof(sa)) != 0) {
        int e = errno;
        close(fd);
        return fail(TAHINI_ERR_CONNECT, "connect %s:%u: %s", ip, (unsigned)port, strerror(e));
    }

    size_t cap = 8192, len = 0;
    char* buf = malloc(cap);
    if (!buf) { close(fd); return fail(TAHINI_ERR_MEMORY, "out of memory"); }

    for (;;) {
        if (len + 1 >= cap) {
            if (cap >= TAHINI_MAX_DOCUMENT) {
                free(buf); close(fd);
                return fail(TAHINI_ERR_PROTOCOL, "document exceeds %d bytes", TAHINI_MAX_DOCUMENT);
            }
            size_t ncap = cap * 2;
            char* nb = realloc(buf, ncap);
            if (!nb) { free(buf); close(fd); return fail(TAHINI_ERR_MEMORY, "out of memory"); }
            buf = nb; cap = ncap;
        }
        ssize_t n = read(fd, buf + len, cap - len - 1);
        if (n > 0) { len += (size_t)n; continue; }
        if (n == 0) break;                      // sidecar closed: document complete
        if (errno == EINTR) continue;
        free(buf); close(fd);
        return fail(TAHINI_ERR_READ, "read: %s", strerror(errno));
    }
    close(fd);
    buf[len] = '\0';

    if (len == 0) { free(buf); return fail(TAHINI_ERR_PROTOCOL, "sidecar sent nothing"); }

    int version = 0;
    if (extract_int(buf, "version", &version) != 0) {
        free(buf);
        return fail(TAHINI_ERR_PROTOCOL, "document has no version field");
    }

    char* hash = extract_string(buf, "binary_hash");
    char* quote = extract_string(buf, "quote");
    char* vinfo = extract_object(buf, "verification_info");
    free(buf);

    // All three or none. A caller that got a hash but no credential could check
    // the manifest and then connect with no way to verify the peer, which is worse
    // than not attesting at all because it looks like it worked.
    if (!hash || !quote || !vinfo) {
        free(hash); free(quote); free(vinfo);
        return fail(TAHINI_ERR_PROTOCOL,
                    "document missing %s%s%s",
                    hash ? "" : "binary_hash ",
                    quote ? "" : "quote ",
                    vinfo ? "" : "verification_info");
    }

    out->version = version;
    out->binary_hash = hash;
    out->quote = quote;
    out->verification_info = vinfo;
    return TAHINI_OK;
}
